# Generated by Django 5.2.6 on 2025-09-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_proveedor_preciohistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('bonificaciones', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('CONFIRMADA', 'CONFIRMADA'), ('ANULADA', 'ANULADA')], default='BORRADOR', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.cliente')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renglon', models.IntegerField(default=1)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('bonif', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_renglon', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'ordering': ['venta_id', 'renglon'],
            },
        ),
    ]
