# render.yaml

services:
  # ... (tu servicio de base de datos psql) ...
  - type: psql
    name: bebidas-db
    plan: free

  # --- Servicio del Backend (Django) ---
  - type: web
    name: bebidas-backend
    env: docker
    rootDir: backend
    plan: free
    # --- LÍNEA MODIFICADA ---
    # Ahora ejecutamos los 3 comandos en el orden correcto
    preDeployCommand: "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py create_superuser_on_deploy"
    dockerCommand: "gunicorn core.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      # ... (tus variables de entorno DATABASE_URL, DJANGO_SECRET_KEY, etc.) ...
      # Asegúrate de que las variables del superusuario siguen aquí o en el panel de Render
      - key: DJANGO_SUPERUSER_USERNAME
        fromEnvironmentVariable: DJANGO_SUPERUSER_USERNAME
      - key: DJANGO_SUPERUSER_EMAIL
        fromEnvironmentVariable: DJANGO_SUPERUSER_EMAIL
      - key: DJANGO_SUPERUSER_PASSWORD
        fromEnvironmentVariable: DJANGO_SUPERUSER_PASSWORD