services:
  - type: psql
    name: bebidas-db
    plan: free

  - type: web
    name: bebidas-backend
    env: docker
    rootDir: backend
    plan: free
    
    # --- PRUEBA FINAL: AISLAR MIGRATE ---
    # Ejecutamos ÚNICA Y EXCLUSIVAMENTE el comando de migración.
    # Si esto funciona, el problema es collectstatic.
    # Si esto falla, nos dará el error final y definitivo.
    preDeployCommand: "python manage.py migrate"
    
    dockerCommand: "gunicorn core.wsgi --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: bebidas-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true