services:
  - type: psql
    name: bebidas-db
    plan: free

  - type: web
    name: bebidas-backend
    env: docker
    rootDir: backend
    plan: free
    
    # --- COMANDO DE DIAGNÓSTICO #1 ---
    # 1. ls -la: Lista todos los archivos y sus permisos en el directorio de trabajo (/app).
    # 2. echo ...: Imprime un separador para que el log sea legible.
    # 3. printenv: Imprime TODAS las variables de entorno que el contenedor está viendo.
    preDeployCommand: "ls -la && echo '--- ENV VARS ---' && printenv"
    
    # Mantenemos el dockerCommand igual, aunque no debería llegar a ejecutarse si el preDeployCommand falla.
    dockerCommand: "gunicorn core.wsgi --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: bebidas-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"