services:
  - type: psql
    name: bebidas-db
    plan: free

  - type: web
    name: bebidas-backend
    env: docker
    rootDir: backend
    plan: free
    
    # --- COMANDO DE PRE-DESPLIEGUE FINAL ---
    # Ahora que WhiteNoise est치 bien configurado, ejecutamos ambos comandos.
    # 1. collectstatic: Recopila todos los archivos est치ticos en la carpeta STATIC_ROOT.
    # 2. migrate: Aplica las migraciones a la base de datos de Postgres.
    # El '2>&1' se mantiene como buena pr치ctica para capturar cualquier error.
    preDeployCommand: "python manage.py collectstatic --no-input && python manage.py migrate 2>&1"
    
    dockerCommand: "gunicorn core.wsgi --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: bebidas-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG # A침adimos esta para que el settings.py no falle
        value: "False"