services:
  - type: psql
    name: bebidas-db
    plan: free

  - type: web
    name: bebidas-backend
    env: docker
    rootDir: backend
    plan: free
    
    # --- COMANDO DE PRE-DESPLIEGUE FINAL Y CORRECTO ---
    # 1. collectstatic: Recopila los archivos estáticos para WhiteNoise.
    # 2. migrate: Aplica las migraciones a la base de datos de Postgres.
    preDeployCommand: "python manage.py collectstatic --no-input && python manage.py migrate"
    
    dockerCommand: "gunicorn core.wsgi --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: bebidas-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true