services:
  - type: psql
    name: bebidas-db
    plan: free

  - type: web
    name: bebidas-backend
    env: docker
    rootDir: backend
    plan: free
    
    # El preDeployCommand se elimina. Su lógica ahora vive en el entrypoint.sh.
    
    dockerCommand: "gunicorn core.wsgi --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: bebidas-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true