# Generated by Django 5.2 on 2025-10-06 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_rename_categoria_cliente_categoria_cliente_and_more'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core_app.local'),
        ),
        migrations.AddField(
            model_name='producto',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core_app.local'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='core_app.local'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Nombre de la categoría (ej. Cervezas, Vinos)', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_categoria', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('local', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('local', 'codigo')},
        ),
    ]
