# Generated by Django 5.2.6 on 2025-10-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_categoria_local_producto_local_proveedor_local_and_more'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core_app.local'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='core_app.local'),
            preserve_default=False,
        ),
    ]
