@startuml
left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle

actor "Encargado de Stock/Compras" as Encargado

rectangle "Sistema de Gestión de Bebidas" {
    usecase "Cargar Compra" as CargarCompra
    usecase "Agregar Ítem a Compra" as AgregarItem
    usecase "Alta en línea de Proveedor" as AltaProveedor
    usecase "Alta en línea de Producto" as AltaProducto
}

Encargado -- CargarCompra

CargarCompra .> AgregarItem : <<include>>
AgregarItem .> AltaProveedor : <<include>>
AgregarItem .> AltaProducto : <<include>>

@enduml