# Generated by Django 5.2.6 on 2025-09-07 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_proveedor_preciohistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('bonificaciones', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='catalogo.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renglon', models.PositiveIntegerField(default=1)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('bonif', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_renglon', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
            ],
        ),
    ]
