# Generated by Django 5.2.6 on 2025-10-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_local'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core_app.local'),
            preserve_default=False,
        ),
    ]
